http://10.112.110.111/v1 
key:  sk-43Y6B7acOvFuOPelLuLw8Q
model: minimax-m2.5
 
你可以通过下面命令获得目前支持的模型列表 curl -L -X GET 'http://10.112.110.111/v1/models' -H 'Accept: application/json' -H "Authorization: Bearer sk-43Y6B7acOvFuOPelLuLw8Q"  |jq '.'
 
